---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{VM_IP}`) && ((PathPrefix(`/api`) || PathPrefix(`/dashboard`)))
      services:
        - kind: TraefikService
          name: api@internal
          namespace: kube-system